# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: split_grpc.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10split_grpc.proto\x12\nsplit_grpc\"_\n\x0csplitRequest\x12!\n\x07outputs\x18\x01 \x03(\x0b\x32\x10.split_grpc.Dict\x12\x0b\n\x03tid\x18\x02 \x01(\t\x12\x0b\n\x03sid\x18\x03 \x01(\t\x12\x12\n\nkeep_alive\x18\x04 \x01(\x08\",\n\rsplitResponse\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0b\n\x03sid\x18\x02 \x01(\t\"\"\n\x04\x44ict\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2I\n\x08SPLITRPC\x12=\n\x06\x41ssign\x12\x18.split_grpc.splitRequest\x1a\x19.split_grpc.splitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'split_grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPLITREQUEST']._serialized_start=32
  _globals['_SPLITREQUEST']._serialized_end=127
  _globals['_SPLITRESPONSE']._serialized_start=129
  _globals['_SPLITRESPONSE']._serialized_end=173
  _globals['_DICT']._serialized_start=175
  _globals['_DICT']._serialized_end=209
  _globals['_SPLITRPC']._serialized_start=211
  _globals['_SPLITRPC']._serialized_end=284
# @@protoc_insertion_point(module_scope)
