{
 "title": "Split Assignment Duration per TID",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exported_instance",
    "label": "Executor ID",
    "query": {
     "query": "label_values(batch_started, exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job_num_requests{exported_instance=~\"$exported_instance\", job_label=\"None\"}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job_batch_size{exported_instance=~\"$exported_instance\", job_label=\"None\"}"
    }
   ]
  },
  {
   "title": "Number of Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job_num_splits{exported_instance=~\"$exported_instance\", job_label=\"None\"}"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job_num_task_managers{exported_instance=~\"$exported_instance\", job_label=\"None\"}"
    }
   ]
  },
  {
   "title": "Memory (MB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "job_memory{exported_instance=~\"$exported_instance\", job_label=\"None\"}"
    }
   ]
  },
  {
   "title": "Batch Assignment Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "current_batch{exported_instance=~\"$exported_instance\"}",
     "legendFormat": "Task Manager {{task_manager}}"
    }
   ]
  },
  {
   "title": "Completed Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(batch_finished{exported_instance=~\"$exported_instance\"})"
    }
   ]
  },
  {
   "title": "Job Latency (s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(job_finished_timestamp{exported_instance=~\"$exported_instance\"} - job_start_timestamp{exported_instance=~\"$exported_instance\"}) or (time() - job_start_timestamp{exported_instance=~\"$exported_instance\"})"
    }
   ]
  },
  {
   "title": "Throughput (req/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (batch_id) (split_inputs_count{exported_instance=~\"$exported_instance\"})) / (max(max by (batch_id) (batch_finished{exported_instance=~\"$exported_instance\"})) - min(min by (batch_id) (batch_started{exported_instance=~\"$exported_instance\"})))"
    }
   ]
  },
  {
   "title": "Average Batch Latency (s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(max by (exported_instance, task_manager, batch_id) (batch_finished{exported_instance=~\"$exported_instance\"}) - min by (exported_instance, task_manager, batch_id) (batch_started{exported_instance=~\"$exported_instance\"}))"
    }
   ]
  },
  {
   "title": "Average Batches per Task Manager",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(count(count_over_time(batch_finished{exported_instance=~\"$exported_instance\"}[6h])) by (task_manager))"
    }
   ]
  },
  {
   "title": "Average Requests per Task Manager",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (task_manager) (split_inputs_count{exported_instance=~\"$exported_instance\"}))"
    }
   ]
  },
  {
   "title": "Total Cost ($)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((job_finished_timestamp{exported_instance=~\"$exported_instance\"} + 0*job_start_timestamp{exported_instance=~\"$exported_instance\"}) or (time() + 0*job_start_timestamp{exported_instance=~\"$exported_instance\"})) - job_start_timestamp{exported_instance=~\"$exported_instance\"}) * job_memory{exported_instance=~\"$exported_instance\"} * job_num_task_managers{exported_instance=~\"$exported_instance\"} * job_cost_per_ms_mb{exported_instance=~\"$exported_instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Job Throughput/Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max by (batch_id) (split_inputs_count{exported_instance=~\"$exported_instance\"})) / (max(max by (batch_id) (batch_finished{exported_instance=~\"$exported_instance\"})) - min(min by (batch_id) (batch_started{exported_instance=~\"$exported_instance\"})))) / sum((((job_finished_timestamp{exported_instance=~\"$exported_instance\"} + 0*job_start_timestamp{exported_instance=~\"$exported_instance\"}) or (time() + 0*job_start_timestamp{exported_instance=~\"$exported_instance\"})) - job_start_timestamp{exported_instance=~\"$exported_instance\"}) * job_memory{exported_instance=~\"$exported_instance\"} * job_num_task_managers{exported_instance=~\"$exported_instance\"} * job_cost_per_ms_mb{exported_instance=~\"$exported_instance\"} * 1000)"
    }
   ]
  },
  {
   "title": "Batches Processed per Task Manager",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(batch_finished{exported_instance=~\"$exported_instance\"}[6h])) by (task_manager)",
     "legendFormat": "Task Manager {{task_manager}}"
    }
   ]
  },
  {
   "title": "Batch Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (exported_instance, task_manager, batch_id) (batch_finished{exported_instance=~\"$exported_instance\"}) - min by (exported_instance, task_manager, batch_id) (batch_started{exported_instance=~\"$exported_instance\"})",
     "legendFormat": "{{batch_id}}"
    }
   ]
  },
  {
   "title": "Active Duration per Task Manager",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(batch_finished{exported_instance=~\"$exported_instance\"}) by (task_manager) - min(batch_started{exported_instance=~\"$exported_instance\"}) by (task_manager)",
     "legendFormat": "Task Manager {{task_manager}}"
    }
   ]
  }
 ]
}