{
 "title": "Detailed Dashboard by Executor ID (Serverless Backend)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "executor_id", "label": "Executor ID", "query": { "query": "label_values(executor_id)" } },
   {
    "name": "call_id",
    "label": "Call ID",
    "query": {
     "query": "label_values({executor_id=\"$executor_id\"},call_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(call_id) (cpu_usage{executor_id=\"$executor_id\", call_id=~\"${call_id}\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg, Min and Max by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cpu_usage{executor_id=\"$executor_id\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(cpu_usage{executor_id=\"$executor_id\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "max(cpu_usage{executor_id=\"$executor_id\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (system_time{executor_id=\"$executor_id\"})",
     "legendFormat": "System Time"
    },
    {
     "expr": "avg by(executor_id) (iowait_time{executor_id=\"$executor_id\"})",
     "legendFormat": "IOwait_time"
    },
    {
     "expr": "avg by(executor_id) (user_time{executor_id=\"$executor_id\"})",
     "legendFormat": "User Time"
    },
    {
     "expr": "avg by(executor_id) (children_user_time{executor_id=\"$executor_id\"})",
     "legendFormat": "Children User Time"
    },
    {
     "expr": "avg by(executor_id) (children_system_time{executor_id=\"$executor_id\"})",
     "legendFormat": "Children System Time"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(call_id) (disk_read_mb{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(call_id) (disk_write_mb{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(call_id) (disk_read_rate{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(call_id) (disk_write_rate{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(call_id) (memory_usage{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(call_id) (net_read_mb{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(call_id) (disk_write_mb{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(call_id) (net_read_rate{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(call_id) (net_write_rate{executor_id=\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}