{
 "title": "Detailed Dashboard per Call ID",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "executor_id", "label": "Executor ID", "query": { "query": "label_values(executor_id)" } },
   {
    "name": "call_id",
    "label": "Call ID",
    "query": {
     "query": "label_values({executor_id=\"$executor_id\"},call_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage{call_id=\"$call_id\", executor_id=\"$executor_id\"}",
     "legendFormat": "{{parent_pid}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(pid) (disk_read_mb{executor_id=\"$executor_id\", call_id=\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(pid) (disk_write_mb{executor_id=\"$executor_id\", call_id=\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(pid) (disk_read_rate{executor_id=\"$executor_id\", call_id=\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(pid) (disk_write_rate{executor_id=\"$executor_id\", call_id=\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(pid) (memory_usage{executor_id=\"$executor_id\", call_id=\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}