{
 "title": "General Performance Dashboard of the Executor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (cpu_usage)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Disk Read by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (disk_read_mb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (disk_write_mb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Rate by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (disk_read_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write rate by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (disk_write_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (memory_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Network Read by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (net_read_mb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Write by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (net_write_mb)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Read rate by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (net_read_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Write rate by executor_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(executor_id) (net_write_rate)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}