{
 "title": "Generic Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "executor_id", "label": "Executor ID", "query": { "query": "label_values(executor_id)" } },
   {
    "name": "call_id",
    "label": "Call ID",
    "query": {
     "query": "label_values(cpu_usage{executor_id=\"$executor_id\"},call_id)"
    }
   },
   {
    "name": "is_standalone",
    "query": {
     "query": "label_values(cpu_usage{executor_id=\"$executor_id\"},worker_name)"
    }
   },
   {
    "name": "worker_instance",
    "label": "Worker Instance",
    "query": {
     "query": "label_values({executor_id=~\"$executor_id\"},worker_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Generic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Execution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(executor_id) (worker_func_end_tstamp{executor_id=\"$executor_id\", call_id=~\"$call_id\"}) - min by(executor_id) (worker_func_start_tstamp)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(parent_pid) (cpu_usage{executor_id=~\"$executor_id\", call_id=~\"$call_id\"}))",
     "legendFormat": "Number of Workers"
    },
    {
     "expr": "count(count by(pid, parent_pid, call_id) (children_system_time{executor_id=~\"$executor_id\", call_id=~\"$call_id\"}))",
     "legendFormat": "Number of Processes"
    },
    {
     "expr": "count(count by(worker_name) (cpu_usage{executor_id=\"$executor_id\", call_id=~\"$call_id\"}))",
     "legendFormat": "Number of Worker Instances"
    }
   ]
  },
  {
   "title": "Execution Time by Call ID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_func_exec_time{executor_id=\"$executor_id\"}",
     "legendFormat": "{{call_id}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(executor_id) (cpu_usage{executor_id=~\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Times",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(executor_id) (system_time{executor_id=~\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "System Time"
    },
    {
     "expr": "sum by(executor_id) (user_time{executor_id=~\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "User Time"
    },
    {
     "expr": "sum by(executor_id) (iowait_time{executor_id=~\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "IO Wait Time"
    },
    {
     "expr": "sum by(executor_id) (children_system_time{executor_id=~\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "Children System Time"
    },
    {
     "expr": "sum by(executor_id) (children_user_time{executor_id=~\"$executor_id\", call_id=~\"$call_id\"})",
     "legendFormat": "Children User Time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(executor_id) (memory_usage{executor_id=~\"$executor_id\", call_id=~\"$call_id\", worker_name=~\"$worker_instance\"})",
     "legendFormat": "Total Memory Usage"
    },
    {
     "expr": "sum by(call_id) (memory_usage{executor_id=~\"$executor_id\", call_id=~\"$call_id\", worker_name=~\"$worker_instance\"})",
     "legendFormat": "{{call_id}}"
    }
   ]
  },
  {
   "title": "Total Disk Read",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(executor_id) (disk_read_mb{executor_id=~\"$executor_id\", call_id=~\"$call_id\", worker_name=~\"$worker_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Write",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(executor_id) (disk_write_mb{executor_id=~\"$executor_id\", call_id=~\"$call_id\", worker_name=~\"$worker_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Read",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(executor_id) (net_read_mb{executor_id=~\"$executor_id\", call_id=~\"$call_id\", worker_name=~\"$worker_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Write",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(executor_id) (net_write_mb{executor_id=~\"$executor_id\", call_id=~\"$call_id\", worker_name=~\"$worker_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}